// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	ACTOR_KIT_HOST: string;
	ACTOR_KIT_SECRET: string;
	REMIX: DurableObjectNamespace<import("./dist/index").Remix>;
	TODO: DurableObjectNamespace<import("./dist/index").Todo>;
	SESSION: DurableObjectNamespace<import("./dist/index").Session>;
}
