packages:
  - packages/core
  - packages/browser
  - packages/react
  - packages/server
  - packages/test
  - packages/xstate
  - packages/xstate-store
  - packages/redux
  - packages/storybook
  - examples/*
  - website
