#:schema node_modules/wrangler/config-schema.json
name = "tanstack-start-actorkit-todo"
compatibility_date = "2024-09-25"

[vars]
ACTOR_KIT_SECRET = "actor-kit-dev-secret"

[[durable_objects.bindings]]
name = "TODO"
class_name = "Todo"

[[migrations]]
tag = "v1"
new_classes = ["Todo"]
