/**
 * Test worker: Counter + Aggregator DOs for fromActorKit integration tests.
 *
 * Counter: simple incrementable counter
 * Aggregator: invokes Counter via fromActorKit, mirrors counter state
 */
import type {
  ActorKitSystemEvent,
  AnyActorServer,
  BaseActorKitEvent,
  CallerSnapshotFrom,
  WithActorKitEvent,
  WithActorKitInput,
} from "actor-kit";
import {
  createActorKitRouter,
  createMachineServer,
  fromActorKit,
} from "actor-kit/worker";
// DurableObject import available via cloudflare:workers in the Workers runtime
import { assign, sendTo, setup } from "xstate";
import { z } from "zod";

// ============================================================================
// Env — uses the Cloudflare.Env generated by `wrangler types`, extended
// with the actor-kit index signature required by ActorKitEnv.
// ============================================================================

export interface Env extends Cloudflare.Env {
  [key: string]: DurableObjectNamespace<AnyActorServer> | unknown;
}

// ============================================================================
// Counter DO
// ============================================================================

const CounterClientEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("INCREMENT") }),
]);

const CounterServiceEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("INCREMENT") }),
]);

const CounterInputPropsSchema = z.object({});

type CounterClientEvent = z.infer<typeof CounterClientEventSchema>;
type CounterServiceEvent = z.infer<typeof CounterServiceEventSchema>;

type CounterEvent = (
  | WithActorKitEvent<CounterClientEvent, "client">
  | WithActorKitEvent<CounterServiceEvent, "service">
  | ActorKitSystemEvent
) &
  BaseActorKitEvent<Env>;

type CounterInput = WithActorKitInput<
  z.infer<typeof CounterInputPropsSchema>,
  Env
>;

type CounterServerContext = {
  public: { count: number };
  private: Record<string, never>;
};

const counterMachine = setup({
  types: {
    context: {} as CounterServerContext,
    events: {} as CounterEvent,
    input: {} as CounterInput,
  },
  actions: {
    increment: assign({
      public: ({ context }) => ({ count: context.public.count + 1 }),
    }),
  },
}).createMachine({
  id: "counter",
  initial: "active",
  context: () => ({ public: { count: 0 }, private: {} }),
  states: {
    active: {
      on: { INCREMENT: { actions: "increment" } },
    },
  },
});

export type CounterMachine = typeof counterMachine;

export const Counter = createMachineServer({
  machine: counterMachine,
  schemas: {
    clientEvent: CounterClientEventSchema,
    serviceEvent: CounterServiceEventSchema,
    inputProps: CounterInputPropsSchema,
  },
  options: { persisted: true },
});

// ============================================================================
// Aggregator DO — uses fromActorKit to connect to Counter
// ============================================================================

const AggregatorClientEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("INCREMENT_COUNTER") }),
]);

const AggregatorServiceEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("NOOP") }),
]);

const AggregatorInputPropsSchema = z.object({});

type AggregatorClientEvent = z.infer<typeof AggregatorClientEventSchema>;

type CounterUpdatedEvent = {
  type: "COUNTER_UPDATED";
  actorType: "counter";
  actorId: string;
  snapshot: CallerSnapshotFrom<CounterMachine>;
  operations: unknown[];
};

type AggregatorEvent = (
  | WithActorKitEvent<AggregatorClientEvent, "client">
  | WithActorKitEvent<z.infer<typeof AggregatorServiceEventSchema>, "service">
  | ActorKitSystemEvent
  | CounterUpdatedEvent
) &
  BaseActorKitEvent<Env>;

type AggregatorInput = WithActorKitInput<
  z.infer<typeof AggregatorInputPropsSchema>,
  Env
>;

type AggregatorServerContext = {
  public: { counterCount: number; counterId: string };
  private: Record<string, never>;
};

const aggregatorMachine = setup({
  types: {
    context: {} as AggregatorServerContext,
    events: {} as AggregatorEvent,
    input: {} as AggregatorInput,
  },
  actors: {
    counterConnection: fromActorKit<CounterMachine>("counter"),
  },
  guards: {
    isCounterUpdated: ({ event }) => event.type === "COUNTER_UPDATED",
  },
  actions: {
    updateCounterSnapshot: assign({
      public: ({ context, event }) => {
        // Guard ensures this is a CounterUpdatedEvent
        const { snapshot } = event as CounterUpdatedEvent;
        return { ...context.public, counterCount: snapshot.public.count };
      },
    }),
    forwardIncrement: sendTo("counterConnection", { type: "INCREMENT" }),
  },
}).createMachine({
  id: "aggregator",
  initial: "active",
  context: ({ input }) => ({
    public: { counterCount: 0, counterId: `counter-for-${input.id}` },
    private: {},
  }),
  states: {
    active: {
      invoke: {
        id: "counterConnection",
        src: "counterConnection",
        // XState's invoke input function receives the init event which carries
        // the machine input, but XState doesn't type it — this cast is required.
        input: ({ context, event }) => {
          const initEvent = event as { input: AggregatorInput };
          return {
            server: initEvent.input.env.COUNTER,
            actorId: context.public.counterId,
            actorInput: {},
            caller: { id: "aggregator", type: "service" as const },
            signingKey: initEvent.input.env.ACTOR_KIT_SECRET,
            eventSchema: CounterServiceEventSchema,
          };
        },
      },
      on: {
        COUNTER_UPDATED: { actions: "updateCounterSnapshot" },
        INCREMENT_COUNTER: { actions: "forwardIncrement" },
      },
    },
  },
});

export type AggregatorMachine = typeof aggregatorMachine;

export const Aggregator = createMachineServer({
  machine: aggregatorMachine,
  schemas: {
    clientEvent: AggregatorClientEventSchema,
    serviceEvent: AggregatorServiceEventSchema,
    inputProps: AggregatorInputPropsSchema,
  },
  options: { persisted: true },
});

// ============================================================================
// Worker entrypoint
// ============================================================================

const router = createActorKitRouter<Env>(["counter", "aggregator"]);

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/health") return new Response("ok");
    if (url.pathname.startsWith("/api/")) return router(request, env);
    return new Response("test worker", { status: 200 });
  },
};
